import type { Metadata } from "next";
import "@workspace/ui/globals.css";
import {
  SidebarInset,
  SidebarProvider,
} from "@workspace/ui/components/sidebar";
import AppSidebar from "@/components/sidebar/app-sidebar";
import SiteHeader from "@/components/site-header";
import { ScrollArea } from "@workspace/ui/components/scroll-area";

export const metadata: Metadata = {
  title: "Regen Staff",
  description: "Generated by create next app",
  robots: { index: false, follow: false },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider
      style={
        {
          "--sidebar-width": "16rem",
          "--sidebar-width-mobile": "20rem",
        } as React.CSSProperties
      }
    >
      <AppSidebar className="flex-0" variant="inset" />
      <main className="flex min-h-screen w-full flex-col">
        <SidebarInset>
          <SiteHeader className="fixed z-50 w-full flex-1 overflow-hidden" />
          <ScrollArea className="mt-12">
            <div className="flex-1 p-4">{children}</div>
          </ScrollArea>
        </SidebarInset>
      </main>
    </SidebarProvider>
  );
}
