import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ModalProvider from "../providers/modal-provider";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { TooltipProvider } from "@workspace/ui/components/tooltip";
import QueryProvider from "@/providers/query-provider";
import { Toaster } from "@workspace/ui/components/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Regen Staff",
  description: "Generated by create next app",
  robots: { index: false, follow: false },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TooltipProvider>
              <ModalProvider>
                <main className="flex min-h-screen w-full flex-col">
                  {children}
                </main>
              </ModalProvider>
            </TooltipProvider>
              <Toaster position="top-right" />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
