import type { Metadata } from "next";
import "@workspace/ui/globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import {
  SidebarInset,
  SidebarProvider,
} from "@workspace/ui/components/sidebar";
import AppSidebar from "@/components/sidebar/app-sidebar";
import SiteHeader from "@/components/site-header";
import { TooltipProvider } from "@workspace/ui/components/tooltip";

export const metadata: Metadata = {
  title: "Regen Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <TooltipProvider>
        <SidebarProvider
          style={
            {
              "--sidebar-width": "20rem",
              "--sidebar-width-mobile": "20rem",
            } as React.CSSProperties
          }
        >
          <AppSidebar variant="inset" />
          <main className="flex min-h-screen w-full flex-col">
            <SiteHeader />
            <SidebarInset>{children}</SidebarInset>
          </main>
        </SidebarProvider>
      </TooltipProvider>
    </ThemeProvider>
  );
}
